package com.sporttown.domain;

/**
 * Created by admin on 24.01.2016.
 */
public enum ServiceName {
    GYMFORONETIME, GYMTO4PM12, GYMALLDAY12, GYMTO4PMMONTH, GYMALLMONTH31, GYMTRAINER12, MASSAGE, YOGA, SAYNA, KROSFIT, SOLARIY, TOWEL, SLIPPERS, FRESH
}
